language: python
dist: xenial
branches:
  only:
  - master
  - stable
matrix:
  include:
    - python: '3.7'
      env:
        - TRAVIS_TEST_NAME="Pylama_only"
      install:
        - 'pip install pylama'
        - 'pip install eradicate'
        - 'pip install .'
      script: pylama src/
    - python: '2.7'
      env:
       - TRAVIS_TEST_NAME="Py27_pytest_nocov"
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-test-py27to36.txt'
        - 'pip install .'
      script: pytest
    - python: '3.5'
      env:
       - TRAVIS_TEST_NAME="Py35_pytest_nocov"
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-test-py27to36.txt'
        - 'pip install .'
      script: pytest
    - python: '3.6'
      env:
       - TRAVIS_TEST_NAME="Py36_pytest_nocov"
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-test-py27to36.txt'
        - 'pip install .'
      script: pytest
    - python: '3.7'
      env:
       - TRAVIS_TEST_NAME="Py37_pytest_cov_codacy"
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-dev.txt'
        - 'pip install .'
      script: pytest --cov-config=.coveragerc
                     --cov=tabbedshellmenus tests/
                     --cov-report term
                     --cov-report html
                     --cov-report xml
                     --cov-report annotate
                     --no-cov-on-fail
      after_success:
        - python-codacy-coverage -r coverage.xml