language: python
dist: xenial
branches:
  only:
  - master
  - stable
matrix:
  include:
    - python: '3.7'
      env:
        - TRAVIS_TEST_NAME="Lint_only"
      install:
        - 'pip install --upgrade pip'
        - 'pip install .'
        - 'pip install -r requirements-ci.txt'
      script:
        - pylama src
        - pylama tests
        - pylama example_app
        - pylint src
        - pylint tests
        - pylint example_app
        - rst-lint *.rst
    - python: '3.6'
      env:
       - TRAVIS_TEST_NAME="Py36_nocodecov"
      install:
        - 'pip install --upgrade pip'
        - 'pip install .'
        - 'pip install -r requirements-ci.txt'
      script: pytest
    - python: '3.7'
      env:
       - TRAVIS_TEST_NAME="Py37_codecov"
      install:
        - 'pip install --upgrade pip'
        - 'pip install .'
        - 'pip install -r requirements-ci.txt'
      script: pytest
      after_success:
        - bash <(curl -s https://codecov.io/bash)
