language: python
dist: xenial
matrix:
  include:
    - python: '3.7'
      install:
        - 'pip install -r requirements.txt'
        - 'pip install pylama'
        - 'pip install eradicate'
        - 'pip install .'
      script: pylama src/
    - python: '2.7'
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-dev-py27to36.txt'
        - 'pip install .'
      script: pytest
    - python: '3.5'
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-dev-py27to36.txt'
        - 'pip install .'
      script: pytest
    - python: '3.6'
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-dev-py27to36.txt'
        - 'pip install .'
      script: pytest
    - python: '3.7'
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-dev.txt'
        - 'pip install .'
      script: pytest
      after_success:
        - coverage xml
        - python-codacy-coverage -r coverage.xml