language: python
dist: xenial
branches:
  only:
  - master
  - stable
matrix:
  include:
    - python: '3.7'
      env:
        - TRAVIS_TEST_NAME="Pylama_only"
      install:
        - 'pip install pylama'
        - 'pip install eradicate'
        - 'pip install .'
      script: pylama src,tests,example_data_and_app
    - python: '3.5'
      env:
       - TRAVIS_TEST_NAME="Py35"
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-dev.txt'
        - 'pip install .'
      script: pytest
    - python: '3.6'
      env:
       - TRAVIS_TEST_NAME="Py36"
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-dev.txt'
        - 'pip install .'
      script: pytest
    - python: '3.7'
      env:
       - TRAVIS_TEST_NAME="Py37_codecov"
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-dev.txt'
        - 'pip install .'
      script: pytest
      after_success:
        - bash <(curl -s https://codecov.io/bash)