language: python
dist: xenial

matrix:
  include:
    - python: '3.7'
      install:
        - 'pip install pylama'
        - 'pip install eradicate'
        - 'pip install .'
      script: 'pylama src/'
    - python: '2.7'
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-dev-py2735.txt'
        - 'pip install .'
      script: pytest
    - python: '3.5'
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-dev-py2735.txt'
        - 'pip install .'
      script: pytest
    - python: '3.6'
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-dev.txt'
        - 'pip install .'
      script: pytest
    - python: '3.7'
      install:
        - 'pip install -r requirements.txt'
        - 'pip install -r requirements-dev.txt'
        - 'pip install .'
      script: pytest
      after_success:
        - coverage xml
        - python-codacy-coverage -r coverage.xml

# python:
#   - '3.7'
#   - '3.6'
# install:

#   - 'pip install tox-travis'
# script: tox
# after_success:
#   - coverage xml
#   - python-codacy-coverage -r coverage.xml
# script: 'python -m pytest'
# --cov=pyblizzard tests --cov-report=xml'
# after_success:
#  - 'python-codacy-coverage -r coverage.xml'


