language: python
dist: xenial
python:
  - '3.7'
  - '3.6'
install:
  - 'pip install -r requirements.txt'
  - 'pip install -r requirements-dev.txt'
  - 'pip install .'
  - 'pip install tox-travis'
script: tox
after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
# script: 'python -m pytest'
# --cov=pyblizzard tests --cov-report=xml'
# after_success:
#  - 'python-codacy-coverage -r coverage.xml'

