# TODO: add rst linting
language: python
dist: xenial
branches:
  only:
  - master
  - stable
matrix:
  include:
    - python: '3.7'
      env:
        - TRAVIS_TEST_NAME="Lintint_only"
      install:
        - 'pip install .'
        - 'pip install pylama'
        - 'pip install eradicate'
      script: 
        - pylama src,tests,example_app
        - rst-lint *.rst
    - python: '3.6'
      env:
       - TRAVIS_TEST_NAME="Py36_nocodecov"
      install:
        - 'pip install .'
        - 'pip install -r requirements-ci.txt'        
      script: pytest
    - python: '3.7'
      env:
       - TRAVIS_TEST_NAME="Py37_codecov"
      install:
        - 'pip install .'
        - 'pip install -r requirements-ci.txt'       
      script: pytest
      after_success:
        - bash <(curl -s https://codecov.io/bash)