language: python
dist: xenial
python:
  - '3.7'
install:
  - 'pip install pipenv'
  - 'pipenv install'
  - 'pipenv shell'
script: 'python -m pytest'
# --cov=pyblizzard tests --cov-report=xml'
# after_success:
#  - 'python-codacy-coverage -r coverage.xml'